apiVersion: apps/v1
kind: Deployment
metadata:
  name: homechart
  namespace: {{ .Values.global.namespace | quote }}  # Reference the global namespace
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.homechart.replicas }}
  selector:
    matchLabels:
      app: homechart
      service: homechart
  template:
    metadata:
      {{- with .Values.homechart.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: homechart
        service: homechart
        tag: {{ .Values.homechart.deployment.tag }}  # Tag for homechart
    spec:
      {{- with .Values.homechart.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.homechart.deployment.containerName | quote }}  # Editable container name for homechart
          env:
            {{- range $k, $v := .Values.homechart.config.secrets }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: homechart
                  key: {{ $k }}
            {{- end }}
            {{- range $k, $v := .Values.homechart.config.values }}
            - name: {{ $k }}
              value: {{ $k }}
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: HOMECHART_postgresql_hostname
              value: {{ .Values.postgresql.statefulset.hostname | default "postgresql" | quote }}  # Default hostname is "postgresql"
            - name: HOMECHART_postgresql_database
              value: {{ .Values.postgresql.statefulset.database | quote }}  # Database name from statefulset config
            - name: HOMECHART_postgresql_password
              valueFrom:
                secretKeyRef:
                  name: homechart
                  key: HOMECHART_postgresql_password
            - name: HOMECHART_postgresql_username
              valueFrom:
                secretKeyRef:
                  name: homechart
                  key: HOMECHART_postgresql_username
            {{ end }}
          image: {{ .Values.homechart.deployment.repository }}:{{ .Values.homechart.deployment.tag }}  # Image for homechart
          imagePullPolicy: {{ .Values.homechart.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
          resources:
            {{- toYaml .Values.homechart.deployment.resources | nindent 12 }}
      {{- with .Values.homechart.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.homechart.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.homechart.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
