apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homechart
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
  {{- if .Values.homechart.ingress }}
  annotations:
    {{- toYaml .Values.homechart.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.homechart.ingress }}
  ingressClassName: {{ .ingressClassName | quote }}  # Added quote for safety
  rules:
  - host: {{ .host | quote }}  # Added quote for safety
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homechart
            port:
              number: 3000
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .host | quote }}  # Ensure the host matches the rule
      secretName: {{ .tls.secretName | quote }}  # Reference to the TLS secret
  {{- end }}
  {{- end }}
