apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homechart
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.homechart.ingress.annotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.homechart.ingress.ingressClassName | quote }}  # Added quote for safety
  rules:
  - host: {{ .Values.homechart.ingress.host | quote }}  # Added quote for safety
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homechart
            port:
              number: 3000
  {{- with .Values.homechart.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.homechart.ingress.host | quote }}  # Ensure the host matches the rule
      secretName: {{ .Values.homechart.ingress.tls.secretName | quote }}  # Reference to the TLS secret
  {{- end }}
