apiVersion: v1
kind: Service
metadata:
  name: {
      { .Values.postgresql.statefulset.containerName | default "postgresql" },
    } # Default name is "postgresql"
  labels: { { - include "homechart.labels" . | nindent 4 } }
spec:
  ports:
    - port: 5432
      targetPort: 5432 # Should match the containerPort in StatefulSet
      protocol: TCP
      name: postgresql
  selector:
    app: homechart
    service: postgresql
