apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.statefulset.hostname | default "postgresql" | quote }}
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: homechart-postgres
    service: postgresql
