apiVersion: v1
kind: Service
metadata:
  # Default name is "postgresql"
  name:
    {
      {
        .Values.postgresql.statefulset.hostname | default "postgresql" | quote,
      },
    }
  labels: { { - include "homechart.labels" . | nindent 4 } }
spec:
  ports:
    - port: 5432
      targetPort: 5432 # Needs to match the containerPort in StatefulSet
      protocol: TCP
      name: postgresql
  selector:
    app: homechart-postgres
    service: homechart
