apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homechart-postgres
  namespace: {{ .Values.global.namespace | quote }}  # Reference the global namespace
  labels:
    {{- include "homechart.labels" . | nindent 4 }}
spec:
  serviceName: homechart-postgres
  replicas: 1
  selector:
    matchLabels:
      app: homechart-postgres
  template:
    metadata:
      labels:
        app: homechart-postgres
        service: postgres
    spec:
      containers:
        - name: {{ .Values.postgresql.statefulset.containerName | quote }}  # Editable container name for PostgreSQL
          image: {{ .Values.postgresql.statefulset.repository }}:{{ .Values.postgresql.statefulset.tag}}  # Use tag for PostgreSQL
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: homechart
                  key: HOMECHART_postgresql_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homechart
                  key: HOMECHART_postgresql_password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.statefulset.config.database | quote }}  # Database name for PostgreSQL from config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  # Default data directory for PostgreSQL
      volumes:
        {{- if .Values.postgresql.statefulset.existingClaim }}
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.statefulset.existingClaim | quote }}  # Reference to existing PVC
        {{- else }}
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.statefulset.existingClaim | default "postgres-storage" | quote }}  # Optional new PVC if existingClaim not provided
        {{- end }}
